# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8225afb29aa3aaf4aaca71d3ba68119b6a97bdb49ab30c65b5fd2e10399700fbf21b9992980c76baa1ffc0d5dbd04435db5a471d1d25d0031f120b0fc0553976

test:
  secret_key_base: 36902b2cdc49fdd719e13cb660a7128fe6ce5155e8ff9b3c1d0014b5ebea8163cdeda99db63207144ac2104be139380a7cea96410f5cc27975b8373e0578b2fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
